config/routes.rb
Rails.application.routes.draw do
resources :tasks
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/name_of_model.rb
class NameOfModel < ApplicationRecord
end

app/models/task.rb
class Task < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  def index
    @tasks = Task.all
  end

  def show
     @task = Task.find(params[:id])
  end

  def new
     @task = Task.new
  end

  def create
    @task = Task.new(task_params)

    if @task.save
      redirect_to tasks_path
    else
      render :new
    end
  end

  def edit
  end

private
  def task_params
    params.require(:task).permit(:title, :body, :task)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Todo</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/tasks/edit.html.erb
<h1>Tasks#edit</h1>
<p>Find me in app/views/tasks/edit.html.erb</p>

app/views/tasks/index.html.erb
<h1> Tasks </h1>
<% @tasks.each do |task| %>
  <h2><%= task.title %></h2>
  <%= link_to 'Show Task', task_path(task) %>
  <p><%= link_to 'New Task', new_task_path %></p>
<% end %>

app/views/tasks/new.html.erb
<h1>New Task</h1>
<%= form_for @task do |f| %>
  <%= f.label :title %>
  <%= f.text_field :title %>

  <%= f.label :body %>
  <%= f.text_field :body %>

  <%= f.label :task %>
  <%= f.text_area :task %>

  <%= f.submit %>
<% end %>

app/views/tasks/show.html.erb
<h1><%= @task.title %></h1>
<h4><%= @task.body %></h1>
<p><%= @task.task %></p>
<%= link_to 'Back', tasks_path %>